apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: showcase-news
resources:
  - namespace.yaml
  - news-workforce.yaml
  - news-fetcher.yaml
  - summarizer-agent.yaml
  - news-agent.yaml
