---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-gateway
---
apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: AiGateway
metadata:
  name: ai-gateway
  namespace: ai-gateway
spec:
  aiGatewayClassName: litellm
  env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://lgtm.monitoring.svc.cluster.local:4318"
  aiModels:
    - name: gemini-2.5-flash-lite
      provider: gemini
    - name: gemini-2.5-flash
      provider: gemini
