apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-tempo-config
  namespace: showcase-news
data:
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/json"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://lgtm.monitoring.svc.cluster.local:4318"
